##Task1: Create Dataframes and save as csv files

In [1]:
import pandas as pd
import numpy as np

##Creating Employee Dataframe

In [2]:
employee_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Name': ['John Alter','Alice Luxumberg','Tom Sabestine','Nina Adgra','Amy Johny'],
    'Gender': ['M','F','M','F','F'],
    'City': ['Paris','London','Berlin','Newyork','Madrid'],
    'Age': [25,27,29,31,30]
})

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

##save employee CSV in separate cell

In [3]:
employee_df.to_csv('Employee.csv', index=False)

##Creating Seniority dataframe

In [4]:
seniority_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Designation Level': [2,2,3,2,3]
})

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

##Saving Seniority Level DataFrame

In [7]:
seniority_df.to_csv('Seniority.csv', index=False)

##Creating Project Dataframe

In [8]:
project_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005','A002','A005','A003',
           'A001','A003','A001','A004','A004','A005'],
    'Project': ['Project 1','Project 2','Project 3','Project 4','Project 5',
                'Project 6','Project 7','Project 8','Project 9','Project 10',
                'Project 11','Project 12','Project 13','Project 14'],
    'Cost': [1002000,2000000,4500000,5500000,np.nan,680000,400000,
             350000,np.nan,300000,2000000,1000000,3000000,200000],
    'Status': ['Finished','Ongoing','Finished','Ongoing','Finished','Failed',
               'Finished','Failed','Ongoing','Finished','Failed','Ongoing',
               'Finished','Finished']
})

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

##Saving Project Dataframe

In [9]:
project_df.to_csv('Project.csv', index=False)

##Task2: Fill missing cost using running Average(using 'For' Loop )

In [19]:
# Reading Project CSV
project_df = pd.read_csv('Project.csv')

# Calculating running average
cost_sum = 0
count = 0

for i in range(len(project_df)):
    if not pd.isna(project_df.loc[i, 'Cost']):
        cost_sum += project_df.loc[i, 'Cost']
        count += 1
    else:
        project_df.loc[i, 'Cost'] = cost_sum / count

# Check result
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

##Task3: Split Employee name into First name and Last name

In [11]:
# Reading Employee CSV
employee_df = pd.read_csv('Employee.csv')

# Splitting Name column
employee_df[['First Name','Last Name']] = employee_df['Name'].str.split(' ', expand=True)

# Dropping old Name column
employee_df.drop(columns=['Name'], inplace=True)

employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

##Task4: Final Dataframe

In [12]:
# Reading all CSVs
seniority_df = pd.read_csv('Seniority.csv')

# Merge Employee + Seniority
final_df = pd.merge(employee_df, seniority_df, on='ID', how='inner')

# Merge with Project DataFrame
final_df = pd.merge(final_df, project_df, on='ID', how='inner')

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

##Task 5:Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
cost only to employees who have finished the projects.

In [13]:
# Adding Bonus column
final_df['Bonus'] = np.where(final_df['Status'] == 'Finished',
                             final_df['Cost'] * 0.05,
                             0)

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

##Task6:Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.

In [14]:
# Demoting designation for failed projects
final_df.loc[final_df['Status'] == 'Failed', 'Designation Level'] += 1

# Removing employees with designation level > 4
final_df = final_df[final_df['Designation Level'] <= 4]

final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

Task7: Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [15]:
# Adding prefix to First Name
final_df['First Name'] = np.where(final_df['Gender'] == 'M',
                                  'Mr. ' + final_df['First Name'],
                                  'Mrs. ' + final_df['First Name'])

# Dropping Gender column
final_df.drop(columns=['Gender'], inplace=True)

final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

##Task 8: Promote designation level by 1 for the employees whose age is more than 29 years using IF condition.

In [16]:
# Promoting designation for age > 29
final_df.loc[final_df['Age'] > 29, 'Designation Level'] -= 1

final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

##Task9:Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost

In [17]:
# Grouping total cost per employee
total_cost_df = final_df.groupby(['ID','First Name'])['Cost'].sum().reset_index()

# Renaming column
total_cost_df.rename(columns={'Cost':'Total Cost'}, inplace=True)

total_cost_df

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

##Task10: Print all the employee details whose city name contains the letter “o” in it.

In [18]:
# Filtering city names containing 'o'
final_df[final_df['City'].str.contains('o', case=False)]

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0